### ISSUE TITLE
vcfR does not build successfully on Linux

### ISSUE THREAD

**Issue by seantcaron** [knausb/vcfR#58]
R 3.3.2 on Ubuntu 14.04 LTS. vcfR does not build. Initial symptoms are, for some reason, the first character is truncated from the make line generated for each *.cpp file. So what should be:

-I/usr/share/R/include

comes out as:

I/usr/share/R/include

which of course breaks the compilation. But, even hacking around this issue, there are build problems. Here is what I did to make the build complete successfully on my platform, R 3.3.2 on Ubuntu 14.04 LTS:

1. src/vcfRCommon.h needs to contain the line:

#include <errno.h>

When this is done, a new version of the package can be built. It will complain about a checksum mismatch, but the build will proceed.

tar -c -f vcfR_patched_1.4.0.tar.gz vcfR
gzip vcfR_patched_1.4.0.tar.gz

When the below changes (2) and (3) have been made to set up the build environment, this can be installed as usual:

R CMD INSTALL vcfR_patched_1.4.0.tar.gz

2. We need to edit /etc/R/Makeconf to change:

.cpp.o:
	$(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -c $< -o $@

to:

.cpp.o:
	g++ $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -std=c++11 -fPIC -c $< -o $@

It's not clear why when $(CXX) is used, the first character is truncated, if we go and manually interpolate the variable, substituting "g++" then it works fine.

3. We need to edit /usr/share/R/share/make/shlib.mk and change:

$(SHLIB): $(OBJECTS)
	@if test  "z$(OBJECTS)" != "z"; then \
	  echo $(SHLIB_LINK) -o $@ $(OBJECTS) $(ALL_LIBS); \
	  $(SHLIB_LINK) -o $@ $(OBJECTS) $(ALL_LIBS); \
	fi

to:

$(SHLIB): $(OBJECTS)
	@if test  "z$(OBJECTS)" != "z"; then \
	  echo $(SHLIB_LINK) -o $@ $(OBJECTS) $(ALL_LIBS); \
	  g++ -shared -o $@ $(OBJECTS) $(ALL_LIBS); \
	fi

For some reason, SHLIB_LINK is not getting set all. So this starts out attempting to do:

-o vcfR.so NM2WinNM.o RcppExports.o ... vcf_io.o -lz -L/usr/lib/R/lib -lR

Which of course breaks! Manual interpolation "fixes" the issue. It's not clear where SHLIB_LINK is supposed to be set.

I assume someone with more familiarity with writing an R module that uses Rcpp should be able to use this information to fix the build parameters within the library itself, so folks don't have to hack up their R config files to get the build to complete.

**Comment by knausb** [comment]
Hi Sean,

Are you aware of #57? Is this your colleague? I had closed this but reopened it after receiving further communication. If this is the same then these discussions should be merged.

Thank you for your hard work on this! However, I'm not convinced that this is not an issue specific to your system. vcfR is tested on several environments and is currently passing on all.

https://cran.r-project.org/web/checks/check_results_vcfR.html
https://travis-ci.org/knausb/vcfR

Note that Travis is Ubuntu 12.04 and I use 16.04 on my desktops, but it builds in all of these environments. I don't have a test for 14.04 and do acknowledge that it is LTS and should be supported.

I feel the proposals you've made may break the package. For example, your 2 would hardcode the build for g++. R packages need to build on Linux, OSX, windows and even Solaris. These other environments use different compilers and may not have g++ available on their system.

I think we could validate my suspicion that this is system specific if you would like. You can search for other R packages on GitHub by searching for:

    CXX_STD = CXX11 user:cran

(Make sure to click on 'code', the default is repositories.) This should find the src/Makevars file for other R packages with similar dependencies as vcfR. If you undid your fix and tried to install one of these other packages (from CRAN) you may reproduce your issue. If this is true, than I think you need to consider if your R installation has been compromised somehow. If so, you may be best off removing it and installing it again. If I'm wrong, I'd be interested in hearing about it.

Thanks!
Brian

**Comment by seantcaron** [comment]
I just wanted to send a quick follow-up although I apologize that it's not
very timely. Yes, Mao is a colleague of mine; I was asked to see if I could
get this R library to build some weeks back. I'm not really here to tell
you what to do or not do with your own R library, I'm simply relating the
fact that this library appears to have major compile issues on my platform
and the steps I took to ultimately take it to a successful build.

I would not expect you to make the modifications I describe exactly as
stated, you wouldn't want to hard-code those parameters for sure, but the
bug report should relate what's required for the build, that is not being
currently picked up automatically. I suppose the bug report can remain for
others who may also encounter this problem.

I don't feel the build platform is too far out; I've successfully built
over six hundred R libraries on this software load with this R, this
compiler and this userland from CRAN, Bioconductor and elsewhere with
little more than install.packages() and never had any trouble like this.

Best,

Sean

**Comment by zkamvar** [comment]
> I don't feel the build platform is too far out; I've successfully built
over six hundred R libraries on this software load with this R, this
compiler and this userland from CRAN, Bioconductor and elsewhere with
little more than install.packages() and never had any trouble like this.

It's worthwhile to point out that [an earlier comment](https://github.com/knausb/vcfR/issues/57#issuecomment-279853757) revealed that the issue was with packages that require C++11 by showing the same error on an unrelated package that uses C++11. 

The solution might be something as simple as [adding some custom settings](http://stackoverflow.com/a/23414789/2752888) in `~/.R/Makevars`:

```
CXX1X=/usr/local/bin/g++
CXX1XFLAGS += -O3 -Wall -pipe -Wno-unused -pedantic
```

**Comment by knausb** [comment]
I think we have a little miscommunication here. I am used to 'issues' being reports by users who either would like to request a feature or have experienced some sort of unexpected behaviour that they feel is a bug that should be addressed by the developer. I think the poster here is simply trying to document the steps they took in order to get vcfR to work on their system. My current interpretation of the post is that they are not requesting an action by the developer.

Let's summarize. The original post reported a problem installing vcfR on Ubuntu 14.04 LTS. However, vcfR is currently building on travis ci using Ubuntu 12.04 LTS:

https://travis-ci.org/knausb/vcfR

It builds on my desktop (Ubuntu 16.04 LTS). And it checks on CRAN:

https://cran.r-project.org/web/checks/check_results_vcfR.html

Note that there are presently a few issues, some of which have occurred since the last update of vcfR, but these do not appear relevant to the original post. This builds an argument that the problem experienced by the poster may be system specific.

The poster has presented a solution that apparently works on their system and may be of use to others. Thank you!

@zkamvar has made a suggestion on how these comments may be incorporated into the package. However, I do not see a compelling argument that these suggetions should be made to vcfR at the current time as we have not validated that there is a problem with vcfR.

If the original poster agrees with this I suggest they close the thread. The closed thread will still be searchable by search engines and by closing it it will indicate that no action is expected by the developer.

If the poster would like us to pursue this I suggest they revisit https://github.com/knausb/vcfR/issues/57#issuecomment-279848778 where I suggested they attempt to install a package with similar dependencies as vcfR.

Thank you!

**Comment by zkamvar** [comment]
> @zkamvar has made a suggestion on how these comments may be incorporated into the package. However, I do not see a compelling argument that these suggetions should be made to vcfR at the current time as we have not validated that there is a problem with vcfR.

To be clear: I was making a suggestion that OP modify `~/.R/Makevars`, not that @knausb modify `/path/to/vcfR/src/Makevars`.

**Comment by seantcaron** [comment]
Hi! Just following up again! That's correct, I mostly just wanted to
describe what I encountered and how I managed to work around it; I'm sorry
I produced a bug report for this, perhaps not the proper venue. But at the
time, it seemed the easiest way I could get a "FYI" close to the code.

I am happy to try things on my platform here and report back to see if it
gets the package closer to building clean on this platform, Ubuntu 14 with
GCC 4.8 and R 3.3.x. In that vein -

I tried setting up ~/.R/Makevars as suggested by Zhian:

CXX1X=/usr/bin/g++
CXX1XFLAGS += -O3 -Wall -pipe -Wno-unused -pedantic

I had tried tweaking the system Makevars a little bit in my original build
attempt, but I am not so familiar with that and I guess I was poking at the
wrong place ... this time, the compile chugged along for a little while,
but failed eventually with the errors:

vcf_io.cpp: In function ‘Rcpp::NumericVector vcf_stats_gz(std::string)’:
vcf_io.cpp:50:66: error: ‘errno’ was not declared in this scope
     Rcpp::Rcerr << "gzopen of " << x << " failed: " << strerror (errno) <<
".\n";
                                                                  ^
vcf_io.cpp: In function ‘Rcpp::StringVector read_meta_gz(std::string,
Rcpp::NumericVector, int)’:
vcf_io.cpp:123:66: error: ‘errno’ was not declared in this scope
     Rcpp::Rcerr << "gzopen of " << x << " failed: " << strerror (errno) <<
".\n";
                                                                  ^
vcf_io.cpp: In function ‘Rcpp::CharacterMatrix read_body_gz(std::string,
Rcpp::NumericVector, int, int, Rcpp::IntegerVector, int, int)’:
vcf_io.cpp:356:66: error: ‘errno’ was not declared in this scope
     Rcpp::Rcerr << "gzopen of " << x << " failed: " << strerror (errno) <<
".\n";
                                                                  ^
vcf_io.cpp: In function ‘void write_vcf_body(Rcpp::CharacterMatrix,
Rcpp::CharacterMatrix, std::string, int)’:
vcf_io.cpp:574:34: error: no matching function for call to
‘std::basic_ifstream<char>::basic_ifstream(std::string&)’
   if ( ! std::ifstream( filename ) ){
                                  ^
vcf_io.cpp:574:34: note: candidates are:
In file included from vcf_io.cpp:2:0:
/usr/include/c++/4.8/fstream:467:7: note: std::basic_ifstream<_CharT,
_Traits>::basic_ifstream(const char*, std::ios_base::openmode) [with _CharT
= char; _Traits = std::char_traits<char>; std::ios_base::openmode =
std::_Ios_Openmode]
       basic_ifstream(const char* __s, ios_base::openmode __mode =
ios_base::in)
       ^
/usr/include/c++/4.8/fstream:467:7: note:   no known conversion for
argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
/usr/include/c++/4.8/fstream:453:7: note: std::basic_ifstream<_CharT,
_Traits>::basic_ifstream() [with _CharT = char; _Traits =
std::char_traits<char>]
       basic_ifstream() : __istream_type(), _M_filebuf()
       ^
/usr/include/c++/4.8/fstream:453:7: note:   candidate expects 0 arguments,
1 provided
/usr/include/c++/4.8/fstream:427:11: note:
std::basic_ifstream<char>::basic_ifstream(const std::basic_ifstream<char>&)
     class basic_ifstream : public basic_istream<_CharT, _Traits>
           ^
/usr/include/c++/4.8/fstream:427:11: note:   no known conversion for
argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const
std::basic_ifstream<char>&’
vcf_io.cpp:580:60: error: no matching function for call to
‘std::basic_ofstream<char>::open(std::string&, std::_Ios_Openmode)’
     myfile.open (filename, std::ios::out | std::ios::binary);
                                                            ^
vcf_io.cpp:580:60: note: candidate is:
In file included from vcf_io.cpp:2:0:
/usr/include/c++/4.8/fstream:713:7: note: void std::basic_ofstream<_CharT,
_Traits>::open(const char*, std::ios_base::openmode) [with _CharT = char;
_Traits = std::char_traits<char>; std::ios_base::openmode =
std::_Ios_Openmode]
       open(const char* __s,
       ^
/usr/include/c++/4.8/fstream:713:7: note:   no known conversion for
argument 1 from ‘std::string {aka std::basic_string<char>}’ to ‘const char*’
vcf_io.cpp:604:75: error: ‘errno’ was not declared in this scope
       Rcpp::Rcerr << "gzopen of " << filename << " failed: " << strerror
(errno) << ".\n";
                                                                           ^
make: *** [vcf_io.o] Error 1
ERROR: compilation failed for package ‘vcfR’

It looks like it's still a little confused about errno. I'm not clear - and
my original bug report evinces this - if errno is sort of supposed to be
"implied" in C++11, but G++ isn't picking up on this ... maybe it needs the
-std=c++11 flag in Makevars, too? Strange it's so finicky here.

Best,

Sean

**Comment by knausb** [comment]
Hi Sean,

Thanks for sticking with us on this! Your help is appreciated!

I've validated that vcfR builds on Ubuntu14.4 using Docker. This can be done as follows.

```
host$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
host$ sudo docker run --rm -ti ubuntu:14.04 
```

This should spawn the Docker container. If you have not previously used this containiner it may take a bit to download.

```
guest# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

If we simply install R now we will install an out of date version. [This link](https://www.digitalocean.com/community/tutorials/how-to-set-up-r-on-ubuntu-14-04) provides an example of how we can install the current version.

```
guest# sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list'
guest# gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9
guest# gpg -a --export E084DAB9 | sudo apt-key add -
guest# sudo apt-get update
```

We can now install R. (This will take a bit.)

```
guest# sudo apt-get -y install r-base
```

Once we have installed R we can enter R and install vcfR. (This will take a bit because all of the dependencies will need to be installed on this clean version of R.)

```
guest# R

R version 3.3.3 (2017-03-06) -- "Another Canoe"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
guestR> install.packages('vcfR')
guestR> library('vcfR')

   *****       ***   vcfR   ***       *****
   This is vcfR 1.4.0 
     browseVignettes('vcfR') # Documentation
     citation('vcfR') # Citation
   *****       *****      *****       *****

guestR> 
```

We have now validated that vcfR builds on Ubuntu 12.4, 14.4 and 16.4.

**Comment by knausb** [comment]
I fear we are trying to make more work for the original poster than is necessary. I feel that Sean has provided a 'fix' that works on his system and he has documented this fix on this forum so that others who may have similar problems may find it.

The proposal of @zkamvar is to add compile time options to the `~/.R/Makevars` file. This would be appropriate if there were a desire to implement and deploy this fix as part of an R package. Because R packages need to build in several environments an R package developer adds compile time options to the `~/.R/Makevars` file instead of hard coding them somewhere. My understanding of this is that this allows these options to be interpreted differently depending on what environment (OS) and what compilers may be available. Because there appears to be no desire to implement this fix in an R package I feel that the solution of the OP is adequate. They will probably have to follow the same steps if they choose to upgrade vcfR. But because this appears to be system specific I see no reason why the posted solution should not be considered adequate. @zkamvar is there something you see here that I do not?

If Sean is interested in testing my assertion that this is a system specific issue you could attempt to install other software that has similar dependencies. This can be accomplisher by querying GitHub as follows.

```
-std=c++11 user:cran
```

(Don't forget to click on the 'code' button.) This should display the `Makevars` files for R packages with this dependency. Once you have found other packages you can attempt to install them using `install.packages()`. Note that this was attempted by your colleague: https://github.com/knausb/vcfR/issues/57#issuecomment-279853757.

Thank you for your help and sorry if this has become drawn out!

**Comment by zkamvar** [comment]
@knausb,

> ... Because R packages need to build in several environments an R package developer adds compile time options to the ~/.R/Makevars file instead of hard coding them somewhere.
> ... is there something you see here that I do not?

### `~/.R/Makevars` is a user-specific file.

The developers don't get to touch `~/.R/Makevars` because it's a file that lives in the user's home folder, disconnected from any R package. As I mentioned in my earlier comment, I was never suggesting that the Makevars file in vcfR be modified. I was simply suggesting an avenue that OP may not have explored before.

The `~/.R/Makevars` file is useful because it allows the user to specify things like specific compilers and compiler flags to use. For example, on OSX, the default compiler is clang, which does not have openMP support. I set my compiler in `~/.R/Makevars` to be `/usr/bin/gcc` and add the -fopenmp flag so that I can compile openMP packages.

**Comment by knausb** [comment]
Whoa cowboy! That's an awfully large bold font you're using there. I think its important to remember that this is supposed to be a friendly forum where people can get help. I think that a simple reminder that you meant `~/.R/Makevars` as opposed to `PACKAGE_ROOT/src/Makevars` would have been effective.

I don't agree that this is the best solution. Because this change would be in `~/.R/` it will affect all packages installed by this user subsequent to this change. You're effectively customizing the system. And unless the user is an avid R enthusiast this creates the potential to create other problems down the line. If the user maintains their system as close to 'out of the box' as possible, they will have better luck in getting help from others. The more a user customizes their system the more they are obligated to support their system themselves.

I don't feel that this discussion is heading in a productive direction. The original post provided a solution that has resulted in a successful install. We have agreed that this may be specific to their system. So I think this thread should be closed as resolved.
